import { createStateStore } from '@json-render/core';
import { JSONUIProvider, Renderer } from '@json-render/react';
import { useRef, useState } from 'react';
import {
  type ChatMessage,
  type UiSubmission,
  uiIntentSchema,
  uiSubmissionSchema,
} from '../../server/messages/contract.js';
import { Button } from '../components/upstream/shadcn-ui/components/ui/button.js';
import { useAction } from '../platform/action.js';
import {
  UiCheckbox,
  UiInput,
  type UiProps,
  UiSelect,
  UiTextarea,
} from './presentation-controls.js';

function UiTable({ element }: UiProps<'Table'>) {
  const [table] = useState(() => ({
    columns: element.props.columns.map((label) => ({
      id: crypto.randomUUID(),
      label,
    })),
    rows: element.props.rows.map((row) => ({
      id: crypto.randomUUID(),
      cells: row.map((text) => ({
        id: crypto.randomUUID(),
        text,
      })),
    })),
  }));

  return (
    <div className="overflow-x-auto">
      <table className="w-full text-left text-sm">
        <thead>
          <tr>
            {table.columns.map((column) => (
              <th key={column.id} className="border-b p-2 font-medium">
                {column.label}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {table.rows.map((row) => (
            <tr key={row.id}>
              {row.cells.map((cell) => (
                <td key={cell.id} className="border-b p-2">
                  {cell.text}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

const registry = {
  Card: ({ element, children }: UiProps<'Card'>) => (
    <section
      aria-label={element.props.title}
      className="grid min-w-0 gap-4 rounded-xl border bg-card p-4 text-card-foreground"
    >
      <h3 className="font-medium">{element.props.title}</h3>
      {children}
    </section>
  ),
  Stack: ({ element, children }: UiProps<'Stack'>) => (
    <div
      className={
        element.props.direction === 'horizontal'
          ? 'flex min-w-0 flex-wrap gap-4'
          : 'grid min-w-0 gap-4'
      }
    >
      {children}
    </div>
  ),
  Text: ({ element }: UiProps<'Text'>) => (
    <p className="whitespace-pre-wrap break-words text-sm">{element.props.text}</p>
  ),
  Table: UiTable,
  Input: UiInput,
  Textarea: UiTextarea,
  Select: UiSelect,
  Checkbox: UiCheckbox,
  Button: ({ element, emit, loading }: UiProps<'Button'>) => (
    <Button type="button" disabled={loading} onClick={() => emit('press')}>
      {element.props.label}
    </Button>
  ),
};

export function Presentation({
  messageId,
  ui,
  ready,
  submit,
}: {
  messageId: string;
  ui: NonNullable<ChatMessage['ui']>;
  ready: boolean;
  submit: (input: UiSubmission) => Promise<void>;
}) {
  const [store] = useState(() => createStateStore(ui.answer?.values ?? ui.spec.state));
  const [sent, setSent] = useState(ui.submitted);
  const submitting = useRef(false);
  const action = useAction();
  const disabled = !ready || sent || ui.submitted || action.busy;
  const handlers = {
    submit: async (params: Record<string, unknown>) => {
      if (disabled || submitting.current) return;

      submitting.current = true;
      try {
        await action.run(async () => {
          const { intent } = uiIntentSchema.parse(params);
          await submit(
            uiSubmissionSchema.parse({
              messageId,
              intent,
              values: store.getSnapshot(),
            }),
          );
          setSent(true);
        });
      } finally {
        submitting.current = false;
      }
    },
  };

  return (
    <div className="grid min-w-0 gap-2">
      <p className="text-xs text-muted-foreground">
        Generated by Clef. Answers return to the model. Do not enter secrets.
      </p>
      <JSONUIProvider registry={registry} store={store} handlers={handlers}>
        <Renderer spec={ui.spec} registry={registry} loading={disabled} />
      </JSONUIProvider>
      {(sent || ui.submitted) && (
        <p role="status" className="text-sm text-muted-foreground">
          Answers sent.
        </p>
      )}
      {action.error && (
        <p role="alert" className="text-sm text-destructive">
          {action.error}
        </p>
      )}
    </div>
  );
}
